### ISSUE TITLE
Fails to Copy EFS files on Creators Update

### ISSUE THREAD

**Issue by BennettStaley** [Wunkolo/UWPDumper#2]
As the title says, it fails whenever it hits an EFS file on the creators update. Has anyone else experienced this? Or is it just my machine?

**Comment by Wunkolo** [comment]
Can't seem to reproduce this. Any specific app that this is happening to? It's possible that they blocked certain dumping methods in the _latest_ apps.

**Comment by BennettStaley** [comment]
Interesting then perhaps it IS an issue with my machine.

Pre Creators update Forza Horizon 3 was dumping just fine. Post Creators update and it breaks at:
   bink2winrt_x64.uni10.dll - the first EFS file after all the manifests and signatures.

Using the injector with elevated privileges doesn't help either. Downloaded or Compiled Dlls make no difference, and I tried every working version up until your latest commit.

**Comment by Wunkolo** [comment]
It feels like they may have blocked direct file copies between EFS and the regular file system in the Creator update.
[Currently UWPDump uses a pretty naive standard-library file-copy between the EFS and the non-EFS TempState folder](https://github.com/Wunkolo/UWPDumper/blob/master/UWPDumper/main.cpp#L68).
```cpp
fs::copy(
	File.path(),
	WritePath,
	fs::copy_options::update_existing
);
```
I'll do some more testing once I get the creators update on my main dev machine [so that it can relay some more detailed error information at least](https://github.com/Wunkolo/UWPDumper/blob/master/UWPDumper/main.cpp#L79) but I really should just be reading and tunneling file data through the IPC exploit anyways(currently it's only used to relay logging info).

**Comment by BennettStaley** [comment]
When you are referring to the IPC exploit you just mean creating a thread and copying the files because the App itself has access to them, correct?

And yeah I'm aware of how you were performing the copying before, I've modified those exact lines before to handle DLC for Forza. 

Anyways, thanks for look into this. I was genuinely confused when It started breaking. Let me know if you find anything!

**Comment by Wunkolo** [comment]
The IPC(**I**nter**P**rocess **C**ommunication) exploit I mention involves the use of shared segments. Currently there is no way for a UWP process to communicate with other processes but there is a vulnerability for UWP on windows that I found [in which I can mark a segment in the DLL as "shared" and have two processes load the same DLL and they will have a shared pool of run-time memory between them to communicate with](https://github.com/Wunkolo/UWPDumper/blob/master/UWPDumper/source/UWP/DumperIPC.cpp#L92) which bypasses the sandboxing. One process can write to the pool and it will show up in the other instantly since they now share the same physical memory.
![](http://i.imgur.com/zNYkOsg.gif)
All the blue text you see in the dumper console is text from the injected DLL within the UWP process communicated through this IPC exploit.

What might be happening now is that `fs::copy` involves the UWP-Wrapped [CopyFile2](https://msdn.microsoft.com/en-us/library/windows/apps/hh449404.aspx) at some point of its implementation. If it behaves anything like the regular [CopyFile](https://msdn.microsoft.com/en-us/library/windows/apps/aa363851.aspx) when handling encrypted files then this might be the culprit. I can't tell if this is a recently added behavior addition or not.
```
When CopyFile is used to copy an encrypted file, it attempts to encrypt the destination file with the keys used in the encryption of the source file. If this cannot be done, this function attempts to encrypt the destination file with default keys. If neither of these methods can be done, CopyFile fails with an ERROR_ENCRYPTION_FAILED error code.
```
Can't verify anything right now but option one is to just buffer the source file into memory and write to another one rather than calling "CopyFile" directly or just moving it all over to sending file data over the IPC memory pool(which will probably make the dump a lot slower).

**Comment by BennettStaley** [comment]
Well I seem to have fixed my issue. 
Replacing
`			fs::copy(
				File.path(),
				WritePath,
				fs::copy_options::update_existing
			)`

With
`
			std::ifstream ifs(File.path(), std::ios::binary);
			std::ofstream ofs(WritePath, std::ios::binary);
			ofs << ifs.rdbuf();
`

**Comment by Wunkolo** [comment]
This is precisely the `buffer the source file into memory and write to another one rather than calling "CopyFile" directly` option. Good to know it works since it's just reading an encrypted file like any other privilaged-UWP process. I'll push a commit later with this method implemented while pecking at an IPC implementation.

**Comment by BennettStaley** [comment]
Interesting, I assumed so. If you can't tell I'm extremely new to C++, but I'm very well versed in general CS ideas.

Thanks for all the help!
