### ISSUE TITLE
Add functionality to change dump folder location

### ISSUE THREAD

**Issue by HunterAP23** [Wunkolo/UWPDumper#22]
My Windows installation is on an SSD, and my appdata folder is on that SSD.
I'd like to be able to change the folder location where the files get extracted to, so my OS SSD doesn't get worn out anymore than it has to.

I figured either adding a command line argument or a prompt for the user to appear after the program is run would be fine enough.

**Comment by Wunkolo** [comment]
This is not possible due to the way that UWP works.
UWP applications can only access a small set of folders that both the OS and the UWP-Space application can both see and freely write to. `TempState` is one of them and is the folder I had decided to use which is unfortunately on whatever drive the Operating System is on.
I cannot make UWP write to any folder on the operating system unless the UWP software being dumped is allowed to do such a thing on its own, which most games worth dumping don't do or need to do

**Comment by tunip3** [comment]
@HunterAP23 could a workaround be using symlinks

**Comment by tunip3** [comment]
neither symlinks nor junctions work, I have not tried hardlinks but the fact that it would have to be on the same drive negates its usefulness

**Comment by tunip3** [comment]
> This is not possible due to the way that UWP works.
> UWP applications can only access a small set of folders that both the OS and the UWP-Space application can both see and freely write to. `TempState` is one of them and is the folder I had decided to use which is unfortunately on whatever drive the Operating System is on.
> I cannot make UWP write to any folder on the operating system unless the UWP software being dumped is allowed to do such a thing on its own, which most games worth dumping don't do or need to do

would it be possible to use the [uwp folder picker api ](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/FilePicker/cpp/Scenario3_SingleFolder.xaml.cpp)to pick a directory?

**Comment by Wunkolo** [comment]
Yes, but I don't think it will be able to access any folders outside of what the App already has permission to access.
Ex: Calculator never asks for any kind of file permissions, so having it open the UWP Folder picker will still not allow it to access any folders since its manifest does not ask for those permissions in the first place, and will not be able to write to those folders.

**Comment by tunip3** [comment]
there is a way to accomplish this using symlinks but a way to set the necessary permissions programmatically needs to be figured out

**Comment by tunip3** [comment]
aaaaaaaaaaaa, I found a solution months ago, I tried to reimplement it but I can't remember all of it

**Comment by tunip3** [comment]
nvm

**Comment by HunterAP23** [comment]
Closing this since it was established there's no direct solution due to the constraints of how UWP app permissions work.

**Comment by tunip3** [comment]
> Closing this since it was established there's no direct solution due to the constraints of how UWP app permissions work.

There is a solution, you just need to create a Junction to the directory and add full access permission for all application packages. The only problem is implementing it properly
