### ISSUE TITLE
Feature request:  Allow custom dumping location

### ISSUE THREAD

**Issue by keylimesoda** [Wunkolo/UWPDumper#33]
This tool is commonly used as part of a toolchain for being able to mod UWP games (example:  https://www.reddit.com/r/OutreachHPG/comments/gowlwb/how_to_add_mods_to_mechwarrior_5_mercenaries_pc/)

These games can be in excess of 50GB, which can be hard to fit on OS drive (current default for the tool).  Having the ability to redirect the dump to a custom location will unblock this process for many users.

**Comment by keylimesoda** [comment]
After digging in on the code, I can see why this may be tricky.

I tried to add an additional IPC for SetDumpPath, but it looks like the IPC mechanism being used to pass process IDs relies on atomics which don't like strings.

**Comment by keylimesoda** [comment]
Last bit to close this out.

Turns out that when you install a UWP app in a location other than your OS drive, the system creates a series of hard links on your OS drive to the install location.

Functionally this means that when you dump a UWP, it will dump it to a folder on the OS drive that actually redirects to the app's install location.

**Comment by Wunkolo** [comment]
Ah yea these are all similar conclusions that I've made myself on the matter.. I've ran into this issue myself as games have started to simply get _massive_ but UWP virtualization is very tight about what folders you can touch and what you can hardlink and softlink and all that mess.

The Shared-Memory that I use for IPC can do a lot if you use it right(but you have to use the data on the shared pages, so a heap allocation in process 1 will not make sense in process 2, you have to copy it into the shared memory).
I think the better direction for this is to read the file on the UWP side, and the _pump the file data through the IPC_ onto a listening windows-space executable so that it can create and write the file "anywhere" on the OS outside of UWP space.

So rather than a file-copy within UWP, the UWP dumper is telling the windows side to create files and pipes through the file data itself. It may be much slower but it would be the most flexible.
