### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by VuVirt** [Wunkolo/UWPDumper#7]
I was trying to run the dumper in Debug mode and it couldn't find the remote thread ID. Injection was successful, I think, though, because rebuilding the dll in debug mode failed with file locked error. Can you please tell me if this is to be expected? Does UWP prevent debugging somehow?

**Comment by Wunkolo** [comment]
Not sure exactly what you mean by Debug mode here. If UWP Dumper was compiled in debug mode it should still be able to be injected and ran but you should probably be using release mode. I'm not sure if UWP itself blocks debugging as UWP developers need some way to debug their own UWP software during development but if the UWP app is something that is actively protected against debugging like a game it might have some anti-debugging stuff added into the release-build to counter debug attempts.

**Comment by VuVirt** [comment]
First I run Windows 10 Groove app. Then I run the x64/Debug version of UWPInjector. 
The output says:
Remote thread wait timeout: Unable to find target thread

The dump is successful if I run the x64/Release version of UWPInjector.

**Comment by Wunkolo** [comment]
Something about the idea of linking an expansively symbol-ed debug-mode dll into a UWP app tells me it probably doesn't inject properly due to the DLL trying something funky. I never tried to inject it while in debug mode since I knew I wouldn't be able to debug the DLL once injected anyways. Been black-boxing on my end for a while now.
What is possibly happening too is that since the injected DLL has shared memory regions(which is how the DLL and the dumper process "talk") the extra debug information makes the Injector and the Dumper possibly _not_ share the same memory in the MMU.
